project:
  type: website

website:
  title: "Lastnumber Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/tjlastnumber
format:
  html:
    theme: 
      light: cosmo
      dark: cyborg
    css: styles.css

execute:
  freeze: auto

