project:
  type: website

website:
  title: "Lastnumber"
  navbar:
    right:
      - about.qmd
      - projects.qmd
      - icon: github
        href: https://github.com/tjlastnumber
  sidebar:
    style: docked
    search: true
  page-footer: 
    center: 
      - text: "Copyright 2024, Lastnumber"
      - icon: github
        href: https://github.com/tjlastnumber

format: 
  html:
    theme: 
      light: cosmo
      dark: [cyborg, theme-dark.scss]
    css: styles.css
    toc: true

execute:
  freeze: auto

