project:
  type: website

website:
  title: "Lastnumber"
  navbar:
    right:
      - about.qmd
      - projects.qmd
      - icon: github
        href: https://github.com/tjlastnumber
format:
  html:
    theme: 
      light: cosmo
      dark: [cyborg, theme-dark.scss]
    css: styles.css

execute:
  freeze: auto

